"""Candidate interaction segment schema — output of s05_segment."""
from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field


class CandidateSegment(BaseModel):
    """A temporal segment that may contain a physical interaction.

    Generated by rule-based heuristics (proximity, velocity spikes, etc.).
    Passed to the VLM stage for semantic analysis when vlm.enabled=true.
    """

    segment_id: str
    track_ids: list[int] = Field(default_factory=list)
    start_frame: int = Field(ge=0)
    end_frame: int = Field(ge=0)
    start_sec: float = Field(ge=0.0)
    end_sec: float = Field(ge=0.0)
    trigger_reason: str = ""  # e.g. "proximity", "velocity_spike"
    confidence: float = Field(ge=0.0, le=1.0, default=0.0)
    source: str = "rule_based"
    status: Literal["PENDING", "ANALYZED", "SKIPPED"] = "PENDING"
